# Use Node.js and cache packages
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

# Require docker service for building images during tests
services:
  docker

# Do linting, coverage, build Docker image, and make docs (to deploy to Github pages)
script:
  - make lint
  # Temporarily disable pending Minikube integration here
  # - make cover
  - make build
  - make docs

# Upload test coverage to codecov
# See https://docs.codecov.io/v5.0.0/docs/about-the-codecov-bash-uploader
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Prevent Github Pages from using Jekyll
# which causes docs files starting with underscores to be ignored
before_deploy:
  - touch docs/.nojekyll

# Deploy documentation to Github Pages
# See https://docs.travis-ci.com/user/deployment/pages/
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
