# An example Minikube deployment

# Deployment of the stencila/cloud image

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: stencila-cloud-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stencila-cloud-app
    spec:
      containers:

        # Stencila Cloud server
        - name: server-container
          image: stencila/cloud
          # Use  `IfNotPresent` so that Kubernetes does not pull each time and
          # instead uses the latest build (see README)
          imagePullPolicy: IfNotPresent
          env:
            - name: REDEPLOY_DATETIME
              value: REDEPLOY_DATETIME_
            - name: TICKET
              value: 'platypus'
            - name: JWT_SECRET
              value: 'in production this should actually be a secret'
          ports:
            - containerPort: 2000

---

# Expose the server-container for testing

kind: Service
apiVersion: v1
metadata:
  name: stencila-cloud-server
spec:
  type: NodePort
  selector:
    app: stencila-cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000

---

# Allow the default service account to access the k8s API to manage cluster
# https://github.com/fabric8io/fabric8/issues/6840#issuecomment-307560275
# https://github.com/heptio/aws-quickstart/issues/75#issuecomment-315433745
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: stencila-cloud-crb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
