# An example Minikube deployment

# Deployment of the stencila/cloud image

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: stencila-cloud-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stencila-cloud-app
    spec:
      containers:
        - name: server-container
          image: stencila/cloud
          # Use  `IfNotPresent` so that Kubernetes does not pull each time and
          # instead uses the latest build (see README)
          imagePullPolicy: IfNotPresent
          env:
            - name: REDEPLOY_DATETIME
              value: REDEPLOY_DATETIME_
            - name: STENCILA_CORE_IMAGE
              value: stencila/core@sha256:1b1ddf26b8818d5fdee8f24eed2c074a6572dd8958fdc55f234416e7344ec7ea
            - name: JWT_DISABLE
              value: 'true'
            - name: STORAGE_PVC
              value: storage-pvc
          ports:
            - containerPort: 2000

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  # Minikube will persist files stored under /data so we use that to simulate
  # a persistent disk in production
  # See https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md
  hostPath:
    path: /data/storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

# Expose the server-container for testing

kind: Service
apiVersion: v1
metadata:
  name: stencila-cloud-server
spec:
  type: NodePort
  selector:
    app: stencila-cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000

---

# Allow the default service account to access the k8s API to manage cluster
# https://github.com/fabric8io/fabric8/issues/6840#issuecomment-307560275
# https://github.com/heptio/aws-quickstart/issues/75#issuecomment-315433745
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: stencila-cloud-crb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
